### ISSUE TITLE
CSRF tokens become outdated when page has not been reloaded a long time

### ISSUE THREAD

**Issue by nicolasfranck** [ugent-library/biblio-backoffice#1025]
Some links that use htmx to send updates to the server depend on an event handler
in [csrf.js](https://github.com/ugent-library/biblio-backoffice/blob/dev/assets/js/ui/csrf.js#L2) to automatically
add a CSRF token to the request header. Unfortunately that token is part of the document,
and if the page has not been reloaded in a long time, that token becomes outdated, i.e. invalid,
and the user gets a page like "invalid csrf token".

Of course that may happen also to forms that open in a modal, but it is probably less expected
behaviour as the page is not in "edit mode".

**Comment by netsensei** [comment]
We use gorilla/csrf to generate the tokens.  So looking at https://github.com/gorilla/csrf/blob/master/csrf.go, I notice two things.

gorilla/csrf uses it's [own cookiestore](https://github.com/gorilla/csrf/blob/93379db1992f1b2fbdd4ba1b55a1bf0414b0535e/csrf.go#L182) internally, independent of the cookiestore we use to manage session data. You can pass a [MaxAge](https://github.com/gorilla/csrf/blob/93379db1992f1b2fbdd4ba1b55a1bf0414b0535e/csrf.go#L83) option to `csrf.Protect` which allows you to set when a cookie expires. The [defaultAge](https://github.com/gorilla/csrf/blob/93379db1992f1b2fbdd4ba1b55a1bf0414b0535e/csrf.go#L29) is set at 12 hours. Since we don't explictly configure `MaxAge`, that's how long a csrf cookie will last.

12 hours should be plenty enough, but I can see a scenario where someone starts editing a record late during the day, keeps the browser tab open while suspending their machine (laptop/desktop) and tries to continue the next morning, moving beyond `MaxAge`. Then again, I think that would be an exceptional scenario.

**Comment by nicolasfranck** [comment]
@netsensei indeed, I remember that the page was indeed open for a day, and then I clicked one of the links.

In the long run maybe show some page like "page outdated, please reload" or something.
Of course a bit vague.

**Comment by netsensei** [comment]
@nics @nicolasfranck What's the status on this issue? Can this be closed?

**Comment by nicolasfranck** [comment]
Probably not a problem in a real situation
