### ISSUE TITLE
DOI import fails, leaves blank screen for 2 DOIs

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1035]
# Bug description

DOI import fails, leaves blank screen:
- 10.1007/s00423-022-02687-2
- 10.1245/s10434-022-12387-2 
<img width="1366" alt="Scherm­afbeelding 2023-03-15 om 12 17 55" src="https://user-images.githubusercontent.com/1572885/225294253-c418a42d-63e8-4651-b4b5-567b42a79266.png">

# Steps to Reproduce

1. Go to biblio test and add a publication via DOI https://backoffice.bibliotest.ugent.be/publication/add?method=identifier

2. Add DOI 10.1007/s00423-022-02687-2
<img width="1095" alt="Scherm­afbeelding 2023-03-15 om 12 32 39" src="https://user-images.githubusercontent.com/1572885/225296895-2fd8bed6-166d-46c4-a6fc-1931acd503a1.png">

3. See blank screen, no console log
<img width="1366" alt="Scherm­afbeelding 2023-03-15 om 12 17 55" src="https://user-images.githubusercontent.com/1572885/225294253-c418a42d-63e8-4651-b4b5-567b42a79266.png">

Nuance: this error will not be thrown in the production environment because it already has been added by someone else.
<img width="936" alt="Scherm­afbeelding 2023-03-15 om 12 18 20" src="https://user-images.githubusercontent.com/1572885/225294575-9e0c4cc7-4918-4f49-8bca-eb0960776e28.png">

# Expected behavior
A. The import flows through
B. An error is thrown, such as
<img width="431" alt="Scherm­afbeelding 2023-03-15 om 12 30 25" src="https://user-images.githubusercontent.com/1572885/225296424-995d144c-6cf3-4ecb-801a-5805fa91718b.png"> 

# Risk classification

## Likelihood
- These specific DOIs: 1 (frequent, with every try)
- Other DOIs: under investigation (probably 4, remote or even improbable)

*How often does this happen? 1: Frequent, 2: Probable, 3: Occasional, 4: Remote, 5: improbable 6: incredible*

## Consequences
Impact: 4 (negligible)
As it only impacts one person right now. However, need to figure out how many researcher this profile represent.

*What's the impact? 1: Catastrophic, 2: Critical, 3: Marginal, 4: Negligible*

**Comment by netsensei** [comment]
Caused by uncaught validation errors.  I've fixed that, importing faulty records now shows the same error dialog which is also implemented for datasets:

![image](https://user-images.githubusercontent.com/105355/226358308-cdbe59e0-6043-492f-8a37-1ea22686c83a.png)

The actual problem with the two DOI's:

**10.1007/s00423-022-02687-2**

Validation error due to a missing first_name and last_name fields for on of the authors. The publication from WoS contains this:

```json
        {
            "full_name": "on behalf the Scientific, Research Committee of the European-African Hepato-Pancreato-Biliary Association (E-AHPBA)"
        }
```

I do find a corresponding record in biblio: https://biblio.ugent.be/publication/01GV5XFCVJDH2RFQX7VK80Z9NZ

**10.1245/s10434-022-12387-2**

Validation error due to a missing first_name and last_name fields for on of the authors. The publication from WoS contains this:

```json
    {
        "full_name": "on behalf of the Scientific Committee of the European-African Hepato-Pancreato-Biliary Association"
    }
```

I do find a corresponding record in biblio: https://biblio.ugent.be/publication/01GV5WDX11WX2YGFRBGRAXE46B
