### ISSUE TITLE
Biblio times out large file after 4 minutes with not-so-great internet connection.

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1083]
# Bug

Biblio times out large file after 4 minutes with not-so-great internet connection.

Our colleague at the review team tried uploading this file:
https://deliver.lib.ugent.be/share/01GYY9XRHGYWEMQX35FCGENV2E:4333753

It times out after 4 minutes, the pop-up screen never appears. This also happens in the old Biblio.

Note: It did work on my machine and can be found here: https://backoffice.biblio.ugent.be/publication/4333753?redirect-url=%2Fpublication%3Fq%3D4333753%26sort%3Ddate-updated-desc&show=files

**Comment by netsensei** [comment]
I tried uploading the file on the development environment via UGentnet: went without a hitch.

> This also happens in the old Biblio.

So, this issue also occurred in the old Librecat environment?

> not-so-great internet connection

Is this a mobile connection? Some other type of Internet connection?

Uploading a 0.5 Gb file becomes non-trivial on a spotty connection. There are ways to introduce queuing with retries on the side of the browser, until a stable connection is made allowing for a complete download. But this solution only works if the user can achieve a stable connection within a reasonable time. If not, the upload can't succeed and the user will still notice that there's an issue.

**Comment by mietcls** [comment]
@netsensei 
Sorry, let me clarify:
- internet connection of a reviewer working from home. So this should work well. I can ask what the type of internet connection is they have (or do we know based on our contracts at UGent?).
- "old biblio" I meant in the old current production version - as the test environment now has a new update. We tested on https://backoffice.bibliotest.ugent.be/publication/8658647?redirect-url=%2Fpublication (new implementation) and the old implementation on production https://backoffice.biblio.ugent.be/publication/4333753?redirect-url=%2Fpublication%3Fq%3D4333753%26sort%3Ddate-updated-desc&show=files

**Comment by netsensei** [comment]
Just got confirmation as to 1/ timeouts on the server side: there are no timeouts set. The only hard limit is the 2GB max upload size. Beyond that, the time needed to send data isn't limited.

So, that leaves us with 2/ implementing the not-so-happy path. So, we need to consider what / how we're going to show an error to the user when an upload fails.

**Comment by nics** [comment]
@netsensei Traefik sets no limits, but the biblio-backoffice http server has these hardcoded limits:

```
    ReadTimeout:  3 * time.Minute,
    WriteTimeout: 3 * time.Minute,
```

We can increase these a bit.  

@mietcls 

> So, that leaves us with 2/ implementing the not-so-happy path. So, we need to consider what / how we're going to show an error to the user when an upload fails.

This is indeed needed whatever we do with timeouts.

**Comment by netsensei** [comment]
@nics I suggest increasing those to 5 minutes. Should be enough to cover most cases on slower connections. Traefik provides affordances to mitigate flooding requests, should we end up requiring those.

**Comment by nics** [comment]
@netsensei feel free ;-)

**Comment by mietcls** [comment]
I can create an error. What information do we have when this timeout happens? Something in the likes of... "Your upload has been cancelled after 5 minutes. Please check your internet connection, or try uploading a smaller file." or are these lies?

**Comment by netsensei** [comment]
I've bumped the request timeout from 3 minutes to 5 minutes. So, that should help with some slower connections already.

> What information do we have when this timeout happens? 

I'm looking into this. So, the entire upload uses the browser's `XMLHttpRequest` object. It doesn't seem to differentiate  between "the server throws a timeout because this takes too long" and "somewhere between me and the server; the connection got cut".  The only error message I get is "something went wrong while trying to send".

Then again, that does make sense. If the server determines that the request takes too long to receive, that's ultimately caused by a networking issue i.e. a slow network connection. And it's not that different from a connection that got cut somewhere along the wire (i.e. flaky mobile connection). Or even from the server itself becoming unavailable (i.e. crash).

From the perspective of the browser / user, it's all the same: The connection was lost before the upload could finish.

I would suggest a single message along these lines: "Your upload could not be completed due to a connection issue. Please ensure you have a reliable internet connection. You may reload this page to check if you can still connect with the backoffice application."

**Comment by mietcls** [comment]
Thanks. I'll reword this.

**Comment by mietcls** [comment]
Will reopen when question arises again.
