### ISSUE TITLE
DOI import fails for 10.13128/jems-2279-7149-12605

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1088]
# Bug

DOI import fails on test for 10.13128/jems-2279-7149-12605 (https://doi.org/10.13128/jems-2279-7149-12605) – is this a specific DOI that we do not recognise?

It resolves here: https://oajournals.fupress.net/index.php/bsfm-jems/article/view/12605

## Extra context

Reviewer:

> If the doi is not recognized, this is because it is not yet active. This is not a biblio-problem.

Researcher:

> About the doi: it's very strange, because it's an article published a couple of years ago, and the doi is working on doi.org, but for some reason not when I try to import it on the UGent platform.

### Firefox

Tried with both full URL and ID

![Image](https://user-images.githubusercontent.com/1572885/235712611-c420b8cd-6bc4-495c-ad26-f2418e6f23c2.png)
![Image](https://user-images.githubusercontent.com/1572885/235712610-7a58778e-b0be-470b-9b15-ae8c16116eb1.png)

### Safari

![Image](https://user-images.githubusercontent.com/1572885/235712705-78204071-7cf9-434c-9da2-4f04b32fea07.png)

![Image](https://user-images.githubusercontent.com/1572885/235712584-e14c59ec-e9d0-4173-a2eb-28835ddbc196.png)

**Comment by nicolasfranck** [comment]
This works: https://api.datacite.org/dois/10.13128/jems-2279-7149-12605 (that is the importer for datasets)
This doesn't: https://api.crossref.org/works/10.13128/jems-2279-7149-12605 (that is the importer for publications)

I've seen some code in the past where data was sometimes fetched from crossref, and then if not found from datacite, but I am not sure if that is the right way to do it, or you're just getting a false positive.

**Comment by mietcls** [comment]
@nicolasfranck both do not work for me – do you have screenshots? What steps do you take?

What do you mean with the remark about false positives?

**Comment by netsensei** [comment]
@mietcls

* This DOI points towards a publication, not a dataset.
* The publication importer fetches data from CrossRef via the DOI.
* The dataset importer fetches data from DataCite via the DOI.

If you try to fetch data in CrossRef via the DOI - https://api.crossref.org/works/10.13128/jems-2279-7149-12605 - it will thrown an error:

<img width="682" alt="Screenshot 2023-05-03 at 13 33 24" src="https://user-images.githubusercontent.com/105355/235904927-40a3cb24-08ab-411e-8786-0dcd55bf4baf.png">

That's why importing the record via "Add Publications > add via identifier" doesn't work. Under the hood, the backoffice receives garbled output from CrossRef which can't be parsed into a publication record.

Additionally, the same DOI can be used to get a JSON record from the DataCite API - https://api.datacite.org/works/10.13128/jems-2279-7149-12605 - However, that's of no use at this point because DataCite is used to import datasets, not publications.

**Comment by netsensei** [comment]
How to solve this:

* Either wait for the record to appear in CrossRef (if it hasn't been published in CrossRef yet); or inquire with CrossRef since the JSON record is garbled and they might have to fix that.
* We need to consider a human-friendly error message when this happens; for researchers to notify the reviewers and for reviewers to diagnose / remedy.

**Comment by mietcls** [comment]
Thanks both, clear!

@netsensei since the publication has been published a couple of years ago, the record must have appeared in CrossRef, right? Something must have gone wrong by now. Should we inquire CrossRef, or the researcher itself?

We can in any case make a nice error message indeed. I do feel like I don't have a grasp on everything that can go wrong.

Somehow it does want to import in datasets but indeed it's not a dataset.

**Comment by netsensei** [comment]
>  I don't have a grasp on everything that can go wrong

I think we have these classes of problems:

* Record Validation errors  => the CrossRef JSON is valid; but fields are empty, or data is missing)
* JSON Validation errors => The CrossRef JSON itself is invalid (it's not a JSON string; but garbled data)
* API errors => The API returns 4xx or 5xx errors. The former: a record could not be found, or can't be accessed; the latter: the API returns some kind of general system error.
* Connection errors => CrossRef is unreachable (The wire between the Backoffice & Crossref is blocked for whatever technical reason; or the CrossRef API is offline)

I've implemented validation errors in #1035 but the other types of errors will yield a more generic "something went wrong" error pop-up. We could be more specific; but I don't think we want to burden researchers with the minutiae of how an API works, no?  We do want some human-friendly message that gives at least a general idea of what went wrong (e.g. "CrossRef could not be reached at this time, try again later", "The record could not be found with CrossRef", "The record could not be retrieved from CrossRef")

So, if we know how to word the errors, it shouldn't be that hard to make nicer error messages.

**Comment by mietcls** [comment]
I've gotten some help from the data curators / stewards and they discovered that this journal (from Firenze University Press) uses DataCite to create DOIs. The type is correct, but we can't parse this record as a publication. To move forward: 

1. I'll ask them the reviewers / researcher to add this as BibTeX for now (there was an export available).
2. I'll split up this issue to capture the errors.

Thanks!
