### ISSUE TITLE
Can only find researcher based on personnel number

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1156]
# Bug description
We can find this person through their UGent IDs, but not through entering their name.

000181271576
802003002891

# Steps to Reproduce

1. Go to https://backoffice.biblio.ugent.be/publication/01H50N42QHMWC7Z6B8ZD0Y38SY?redirect-url=%2Fpublication%3Fq%3D01H50N42QHMWC7Z6B8ZD0Y38SY%26sort%3Ddate-updated-desc&show=contributors
2. Try to add NAME
3. See empty result
4. Try with UGent IDs

It works

## Expected behaviour

You can also find this person through entering their name.

**Comment by nicolasfranck** [comment]
Problem is bad scoring. The name is in the list of found 1302 results, but we only fetch 25 results (to spare memory, and because no one look further than 50 results I guess?). That is one of the disadvantages of partial search (and more specifically edge ngrams), which happens more often in sql like interface (`where like '%lin%lin`).

Maybe we can a boost on match on fullName (which is not partial)? Apparently "lin" can often be found in other name parts

**Comment by mietcls** [comment]
Has this the fix for this one already been deployed @nicolasfranck?
Would pagination help if this fix does not do it?
