### ISSUE TITLE
ORCID ID does not always show

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1240]
# Bug description
ORCID ID does not always show up:
- [x] in people & affiliations search
- [x] in GISMO
- [x] in "view as"

It _is_ available when the person is connected to a record.

The orcid was connected on:
_Record last modified Sep 21, 2023, 1:46:13 PM UTC_

# Steps to Reproduce

1. Go to https://backoffice.biblio.ugent.be/dataset
2. View as 
3. Add person to dataset (contributor) or publication (author), through search
4. See as added

See screenshots: https://ugentbe-my.sharepoint.com/:w:/g/personal/miet_claes_ugent_be/EcQDR8ByAD1Ijraf9eaOG98B9S4hwQGReXWf0hl7wDZcPQ?e=8vCzU0

# Expected behaviour
- ORCID shows up in view as, in the person search and when they are added in people & affiliations
- ORCID shows up in GISMO

**Comment by nicolasfranck** [comment]
It is of course confusing that the orcid suddenly appears in one screen,
where it was unavailable in a previous look-a-like screen. So I would argue
to add it to the other screen too.

If it does not appear in gismo, it can only be because their information is outdated?
And did not receive data from us? Do they even show this?

**Comment by mietcls** [comment]
Fixed with time
