### ISSUE TITLE
Filtering does not behave as expected

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1320]
# Bug description

Filtering does not behave as expected

## Case 1
When filtering on "unlocked", a locked record still appears.

There was one case that got solved by switching it to unlocked and locked again – that one does not appear in the list any longer. Not sure if this is something that will happen regularly or is a one off.

This record was _recently_ edited, so it would be a recent hiccup – but it also shows with older records (keep scrolling)

### Steps to Reproduce

1. Go to https://backoffice.biblio.ugent.be/publication?q=&f%5Blocked%5D=false&f%5Bstatus%5D=public&f%5Bclassification%5D=A1&f%5Bclassification%5D=A2&f%5Bclassification%5D=A3&f%5Bclassification%5D=A4&f%5Bclassification%5D=B1&f%5Bclassification%5D=B2&f%5Bclassification%5D=B3&f%5Bclassification%5D=C1&f%5Bclassification%5D=C3&f%5Bclassification%5D=D1&f%5Bclassification%5D=P1&f%5Bclassification%5D=V
(unlocked, public, all types selected but "U").
3. See locked record
<img width="1405" alt="Screenshot 2023-11-21 at 11 36 46" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/8761fdfe-daf6-496e-b894-ac994fa04561">

## Case 2
Withdrawn shows public anyways

### Steps to reproduce
Choose Biblio status filter "withdrawn"
See public and withdrawn appear anyways (https://backoffice.bibliodev.ugent.be/publication?q=&f%5Bstatus%5D=returned)
![Screenshot 2024-06-13 at 16 13 54](https://github.com/ugent-library/biblio-backoffice/assets/1572885/404d9da8-b7b8-4e49-b1b0-c326b6506696)

**Comment by nicolasfranck** [comment]
a former reindexation stopped to early?

**Comment by nics** [comment]
ok again after reindexing, closing for now

**Comment by mietcls** [comment]
I can still see new cases appear, this time:

![Screenshot 2023-11-24 at 15 32 48](https://github.com/ugent-library/biblio-backoffice/assets/1572885/6823ef43-1d97-4d62-95d0-9752496a8db6)

Maybe related: when I copy the URL of this record, it looks like this
https://backoffice.biblio.ugent.be/publication/01H4JE867G1TQMA7A58SC4N4Y3?redirect-url=%2Fpublication%3Fq%3D%26f%255Blocked%255D%3Dfalse%26f%255Bstatus%255D%3Dpublic%26f%255Bclassification%255D%3DA1%26f%255Bclassification%255D%3DA2%26f%255Bclassification%255D%3DA3%26f%255Bclassification%255D%3DA4%26f%255Bclassification%255D%3DB1%26f%255Bclassification%255D%3DB2%26f%255Bclassification%255D%3DB3%26f%255Bclassification%255D%3DC1%26f%255Bclassification%255D%3DC3%26f%255Bclassification%255D%3DD1%26f%255Bclassification%255D%3DP1%26f%255Bclassification%255D%3DV

**Comment by nicolasfranck** [comment]
@mietcls is this still a problem? I cannot replicate this.

**Comment by mietcls** [comment]
Yes, found a whole bunch on page 2 (13) and on page 8 (1)

[Page 2:](https://backoffice.biblio.ugent.be/publication?f%5Bclassification%5D%5B0%5D=A1&f%5Bclassification%5D%5B10%5D=P1&f%5Bclassification%5D%5B11%5D=V&f%5Bclassification%5D%5B1%5D=A2&f%5Bclassification%5D%5B2%5D=A3&f%5Bclassification%5D%5B3%5D=A4&f%5Bclassification%5D%5B4%5D=B1&f%5Bclassification%5D%5B5%5D=B2&f%5Bclassification%5D%5B6%5D=B3&f%5Bclassification%5D%5B7%5D=C1&f%5Bclassification%5D%5B8%5D=C3&f%5Bclassification%5D%5B9%5D=D1&f%5Blocked%5D%5B0%5D=false&f%5Bstatus%5D%5B0%5D=public&page=2&page-size=20):

<img width="1512" alt="Screenshot 2024-01-22 at 15 15 07" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/67d6bc28-92eb-459a-818a-9d12852ca454">

Page 8:
<img width="1512" alt="Screenshot 2024-01-22 at 15 13 04" src="https://github.com/ugent-library/biblio-backoffice/assets/1572885/8dddc6c5-0f84-4dc2-824c-028578648e1d">

If you edit them the problem will probably disappear again.
It seems to be a problem for _more recent_ publications  (I started testing on the last page and clicked until I found some, so this was quite painful :p please test beyond page 1 🙏)

**Comment by nicolasfranck** [comment]
Check ES6 instances: biblio-backoffice is using only one node. So that cannot be the problem:

```
BIBLIO_BACKOFFICE_ES6_URL=http://jensen.ugent.be:9200
```

**Comment by nicolasfranck** [comment]
Number of non-deleted publications that are not locked in the database:

```
biblio_backoffice_prod=> select count(*) from publications where date_until is null and not (data->>'locked')::boolean and data->>'status' <> 'deleted';
 count 
-------
 10482
(1 row)
```

Number of non-deleted publications that are not locked in ES: `10496`

**Comment by mietcls** [comment]
Why would you close it if you cannot reproduce it? The problem still persists.

**Comment by mietcls** [comment]
Picking this up after DICT transfer, following up

**Comment by netsensei** [comment]
Investigating this record: 01HRVFJ8XM45WR1M7R0QZAXGPN

On the search overview page with filter "status": "withdrawn": the publication is shown with status "public"
https://backoffice.bibliodev.ugent.be/publication?q=&f%5Bstatus%5D=returned

On the detail page: the publication is shown with status "public"
https://backoffice.bibliodev.ugent.be/publication/01HRVFJ8XM45WR1M7R0QZAXGPN

In the PostgreSQL database, I find 6 snapshots.  These are the last 2 snapshots:

|  snapshot_id | id  | date_from  | date_until  |  publication status |
| -------------|-----|------------|-----------|--------------------|
| 01HRVFJDM33QCAA2KYVSEXBGR4 | 01HRVFJ8XM45WR1M7R0QZAXGPN  | 2024-03-13 09:41:25.891174+01  | 2024-03-13 09:41:26.603889+01  | returned |
| 01HRVFJEACCZEJ7S27Q23FKD1V | 01HRVFJ8XM45WR1M7R0QZAXGPN  | 2024-03-13 09:41:26.603889+01  | NULL  | public |

In the elastic search index `biblio_backoffice_dev_publication`, I find a document for ID: 01HRVFJ8XM45WR1M7R0QZAXGPN which has these properties:

```
{ 
  "date_created": "2024-03-13T08:41:21.076Z",
  "date_updated": "2024-03-13T08:41:25.89Z",
  "legacy": false,
  "locked": false,
  "extern": false,
  "status": "returned",
  "publication_status": "missing"
}
```

So, the record is included in the search results because the status in the index is set to `returned` (withdrawn).  However, the status in the PostgreSQL database for the latest snapshot is set to `public`.  The field data displayed in the summaries of each result doesn't come from the search index: it comes from the database. 

Why is there a mismatch between the search index and postgreSQL?

Take a look at the timestamps between those two snapshots: about 0.71 seconds. So, within less then one second, the status of the publication was changed twice.  This publication was created by automated Cypress testing, hence the rapid sequence of status updates. 

My guess is a concurrency issue either at the level of elastic or at the level of backoffice. I'll do a few tests to see if I can replicate this.

**Comment by mietcls** [comment]
Edit: I understand it's the same issue probably. How do we deal with this mismatch in database and index?

**Comment by nics** [comment]
these issues can only have 2 causes:

1. indexing failed
2. timing issue (older version wins)

both can be addressed, but will take some effort, especially with the current architecture:

1. a combination of more robust incremental indexing (persistent queue, retries etc) + periodic full reindex to fix the cases that remain

2. use Elasticsearch versioning (https://www.elastic.co/guide/en/elasticsearch/reference/6.8/docs-index_.html). This requires that we include an integer version number in each index doc.

@mietcls issue is probably to big to fix if we want a June release

we can mitigate the issue in the meanwhile by doing a daily index switch for example

**Comment by nics** [comment]
as an example, minibiblio handles search doc versioning correctly: https://github.com/ugent-library/minibiblio/blob/4397c1685f3a243c77700435159e6397d37ca05e/opensearchindex/index.go#L99
