### ISSUE TITLE
Remove non public related datasets and publications from frontoffice records

### ISSUE THREAD

**Issue by nics** [ugent-library/biblio-backoffice#1339]
Only public records must be exposed in the frontend
e.g. this dataset contains a related publication that is deleted:

https://biblio.ugent.be/oai?verb=GetRecord&identifier=oai:archive.ugent.be:01H90QQS0DMAGJY747NK78B3X3&metadataPrefix=mods_36

**Comment by nicolasfranck** [comment]
Important:

- now that we are moving away from an OAI inside biblio to a separate OAI fed by biblio-backoffice directly, this logic needs to be added during the update-oai
- in the meantime better to add this to the currently used OAI in biblio itself.

**Comment by nicolasfranck** [comment]
Looking at the code, this cannot be caused by anything in biblio-backoffice:

* https://github.com/ugent-library/biblio-backoffice/blob/main/frontoffice/record.go#L728
* https://github.com/ugent-library/biblio-backoffice/blob/main/frontoffice/record.go#L961

The url https://backoffice.biblio.ugent.be/frontoffice/dataset/01H90QQS0DMAGJY747NK78B3X3 also proves this.

Investigating this in biblio itself.

**Comment by netsensei** [comment]
@nics Is this issue still actionable? Or do we need to close this for now, or give it a status "blocked" / "unclear"?

**Comment by nics** [comment]
@netsensei closing this, update_oai and new oai service do not have this problem
