### ISSUE TITLE
<p> and </p> tags showing in project description

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#1696]
# Bug Description

`<p>` and `</p>` tags showing in project description. We can't show this in production.

We should filter this out. We are aware there are an endless stream of other tags that could possibly filtered out, but we are going for the 80% problem, not the 100% problem for this fix.

Short term, we are solving `<p>` and `</p>` tags only.
Long term, we are asking GISMO to remove it (but they do not have focus for this now)

![Screenshot 2024-08-30 at 09 12 59](https://github.com/user-attachments/assets/dcb0badc-1667-4251-8c48-76b9daab8759)

**Comment by verheyenkoen** [comment]
@mietcls In the aria-attributes PR (#1657) we already used a library [html2text](https://pkg.go.dev/jaytaylor.com/html2text) that strips HTML for the `aria-description` attribute. In that case we convert to markdown, as the pure strip solution also removes hyperlinks. I guess in this case it is less complex to use that as well (but then just strip all the tags) instead of doing custom replaces of individual tags. Or was there another reason to prefer the 80% solution above the 100% solution?

**Comment by nics** [comment]
@verheyenkoen yeah just go with that. 80/20: we will probably mangle a few descriptions (mathematical formula or other specialized markup that looks like tags).
