### ISSUE TITLE
only publish a selection of WoS-imported publications

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#309]
**Describe the improvement**
Currently, when importing multiple publications from WoS, each publication can be edited individually by going to the publication details (e:g: via the 3 dots). However, publishing to Biblio can only be done for all publications from the import.

We want to be able to select some of the publications of the WoS import and publish those. Others can be left on draft (or could maybe be deleted during the add workflow?).

**Comment by mietcls** [comment]
You can now delete before import. Bulk interactions will be reviewed in general.

**Comment by mietcls** [comment]
@sdebodt does this help? Otherwise I'll come over for a second and dive a bit deeper!

You can delete like so:
![Screenshot 2023-08-18 at 12 57 45](https://github.com/ugent-library/biblio-backoffice/assets/1572885/3ad02c9e-9948-48f2-9d3c-3a159ce4ca3d)

You import publications as draft, and then you can – before publishing – delete the publication.
We will improve the import flow, so you can review what you want to actually import as draft.

![Screenshot 2023-08-18 at 12 59 25](https://github.com/ugent-library/biblio-backoffice/assets/1572885/428becc9-6aeb-4445-af17-cee590cb70fc)
You can save all as draft or publish all, but not make selections.

However, after the import all the records saved as draft in any case (they will not be deleted if you decide to go out of the import flow). You could skip the import flow and go to the search overview and select one by one which you want to edit as draft, delete or publish:
![Screenshot 2023-08-18 at 13 01 22](https://github.com/ugent-library/biblio-backoffice/assets/1572885/7e33e873-1cd2-4fb6-a2be-6dfbe3992e43)

![Screenshot 2023-08-18 at 13 00 31](https://github.com/ugent-library/biblio-backoffice/assets/1572885/4467e42f-7897-4102-91ef-1ff6739cab2f)

**Comment by sdebodt** [comment]
It's clear. We can indeed have a workflow in which you exit the import flow and use the publications overview to only keep a selection of the WoS-imported publications. Probably worth describing this in the research tip on WoS import. I will check with Inge.
