### ISSUE TITLE
restrict date/year fields to accepted format

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#326]
**Describe the improvement**
For some fields in which a date or a year is expected, it is not clear from the interface what format should be used.
For dates we want to use the ISO standard (ie. yyyy-mm-dd).

- Publication year
- Conference date
- embargo period (wrong formatting)

example:
Foutmelding is cryptisch (er stond een spatie in het Publication year wat er niet mocht staan) 

![image](https://user-images.githubusercontent.com/72742841/162401311-582bb02c-c63d-4dc1-8c76-d633dc606831.png)

**Comment by nicolasfranck** [comment]
TODO: add placeholder

**Comment by sdebodt** [comment]
related: https://github.com/ugent-library/biblio-backend/issues/278

**Comment by mietcls** [comment]
There are different cases which we cannot capture in one story; to be split up:

Publication year requires freedom – not only YYYY
- Sometimes you do not know what the publication year is (especially for old entrances: s.d. sine dato, approximately this year, ...) 
- Sometimes the date is B.C. (larger context of our library)
- needs freedom, so we avoid _"asking people to lie"_
- We _can_ give guidelines on how to fill it out for consistency, but we should "capture" the essence in the back-end without restricting the user (uniform first, validate after)
-> we need business rules for guidance and to be able to capture the essence. To consult existing best practices.

Conference date also requires freedom
- Sometimes you do not know what the publication date is (especially for old entrances: s.d. sine dato, approximately this year, ...), or they only know the year or month
- Sometimes the date is B.C. (larger context of our library)
- needs freedom, so we avoid _"asking people to lie"_
- We _can_ give guidelines on how to fill it out for consistency, but we should "capture" the essence in the back-end without restricting the user (uniform first, validate after)
-> we need business rules for guidance and to be able to capture the essence. To consult existing best practices.

Embargo period does require exact dates, time stamp
- from YYYY/DD/MM until YYYY/DD/MM
- important to do reasoning on in back-end
- this is okay in this case, because we are not _"asking people to lie"_

**Comment by mietcls** [comment]
Note: weird notation will not happen anymore when new back-end is fixed. Business rules still need to be figured out.

**Comment by mietcls** [comment]
This does not work at the moment, no validation happens on field level. Year can be filled out with plain text atm.

**Comment by mietcls** [comment]
Need to rethink this: 
- Flow for 90% of the population: pick/write a year
- Flow for internal use: be able to add "sd" or approximations.
