### ISSUE TITLE
all form actions should check for conflicts, not only the mutating actions

### ISSUE THREAD

**Issue by nics** [ugent-library/biblio-backoffice#448]
- page gets loaded , set etag in data attr or js
- edit call includes etag in if-match headerr 
- response returns new etag, overwrites old one, or conflict err is shown

note: we don't need dependent objects like projects to have id's anymore when we implement this, we can use indexes again to identify them

**Comment by netsensei** [comment]
@mietcls @nics 

This issue touches on conflicts when multiple users are editing the same record.  Our current approach sets a conflict check per button; and only on buttons that actually "mutate" data (i.e. "update", or "save" or "add project"). This issue describes a way to reduce the amount of code, but also includes a check on all form buttons.

We are (partly) confronted with conflicts because the current design pushes a workflow (create a new record - edit a record) that doesn't actively prevent arising of situations where more then one person are editing the same record; nor notifies users up-front that the someone else is already editing the data.

So, closing this issue as it is a part of a bigger picture discussion we're currently having regarding how we gather / add / edit records.
