### ISSUE TITLE
forms shouldn't use bind structs

### ISSUE THREAD

**Issue by nics** [ugent-library/biblio-backoffice#454]
- should use domain objects, see contributors form

**Comment by nicolasfranck** [comment]
@nics because you want to make them reusable.
Unfortunately the most important forms ("details")
have too much attributes in order to fit in a method.
Every time you change/add an attribute you would
have to rewrite the client code; and doesn't add to
to readability.

This may seem readable:

```
func abstractForm(ctx Context, lang string, text lang, errors validation.Errors) *form.Form
```

but the calling of it is not (what should be where?):

```
abstractForm(ctx, "en", "hello", formErrors);
```

that is the whole reason why we converted this struct syntax

```
struct {
  name string
  value string
} { "name", "value" }
```

to

```
struct {
  name string
  value string
} { name: "name", value: "value" }
```

because sequential arguments are less clear and error prone.

**Comment by nics** [comment]
argument can just be the dataset or publication itself?

**Comment by mietcls** [comment]
Is this something long term we need to figure out and needs to be tracked in #1099 or is this something we need to act on @nics ?

**Comment by nics** [comment]
has already been refactored, can be closed
