### ISSUE TITLE
Reviewers hebben een compacte, volledige view nodig, zonder alles te moeten open klikken (maar ik veronderstel dat dit al op jullie to do staat)

### ISSUE THREAD

**Issue by anniekt** [ugent-library/biblio-backoffice#65]
geen verdere uitleg nodig
******

**Describe the improvement**
A clear and concise description of what the improvement is.

**To Reproduce**
If something does not work as expected, which steps did you take?

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by sdebodt** [comment]
**Describe the improvement**
To speed up the reviewing process and to identify/address incomplete or incorrect metadata, it would be useful to have all metadata sections expanded by default for reviewers, such that they can quickly scroll through the complete record.

**Expected behavior**
When logged in with reviewer status and running through the review workflow, show Publication details page that has an expanded view for all metadata sections. 

In complement to https://github.com/ugent-library/biblio-backend/issues/73

**Comment by nics** [comment]
closing this as outdated
