### ISSUE TITLE
Dashboard does not display all unclassified records, even when they have a department

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#837]
# Bug description

Dashboard does not display all unclassified records, even when they have a department

## Steps to reproduce

Case for dissertations:

1. Go to dashboard, see total dissertations (1)
![Image](https://user-images.githubusercontent.com/1572885/203087320-94b1d57f-601c-4688-9bc9-0b93ca6993b7.png)

2. Go to overview publications and choose filters https://backoffice.biblio.ugent.be/publication?q=&f%5Bstatus%5D=public&f%5Btype%5D=dissertation&f%5Bclassification%5D=U
  1. Choose status "public"
  2. Choose publication type "dissertation"
  3. Classification "U"
  4. See all publications, even with departments
![Image](https://user-images.githubusercontent.com/1572885/203087466-0db1b331-33c5-4610-ad4a-feee054f07b4.png)

## Expected behaviour

Numbers of dashboard are similar to number of records in filter

## Speculation

When clicking the "total" link, and look at all departments, not all of them are checked. They should all be checked.

However, it also seems like some are missing, as I only see three departments with a record attached to it for public dissertations with classification U:

- Faculty of Bioscience Engineering (1)
- Global Campus Korea (1)
- Imec (1)

![Image](https://user-images.githubusercontent.com/1572885/203088561-1dfd896e-5be5-43d3-8e40-a72867f8d0b1.png)

![Image](https://user-images.githubusercontent.com/1572885/203088653-d539e7a8-2a51-4a21-a811-bd93dd819253.png)

![Image](https://user-images.githubusercontent.com/1572885/203088597-ae306c04-cba5-42dc-ae72-5aba27822734.png)

Departments of records in the current case are:
- LA24
- LW03
- PS03
- LA21
- TW05
- PS03
- IMEC
- GE37
- PP09
- LW07
- LA26
- KR01

**Comment by netsensei** [comment]
Looks like a bug where the "faculty" field isn't correctly captured and indexed.

The "faculty" field is derived from the "department" field which contains one (or more) branches from the organizational hierarchy to which the department belongs.  So, for e.g. LW24 the publication stores the entire branch with all its parents including the faculty "LW". During indexation, the faculty/ies is/are extracted from these branches and stored in a separate "faculty" field which is then indexed.

If no faculty could be derived from the "department" field, the "faculty" field will remain empty and the publication won't pop up in search results when the faculty field contains one, multiple or all active facets.

In the example above:

This query explicitly selects publications with "status":"public" and "classification":"U" for 14 faculties (= 14 active facets):

https://backoffice.biblio.ugent.be/publication?f%5Bclassification%5D=U&f%5Bfaculty%5D=all&f%5Bfaculty%5D=CA&f%5Bfaculty%5D=DS&f%5Bfaculty%5D=DI&f%5Bfaculty%5D=EB&f%5Bfaculty%5D=FW&f%5Bfaculty%5D=GE&f%5Bfaculty%5D=LA&f%5Bfaculty%5D=LW&f%5Bfaculty%5D=PS&f%5Bfaculty%5D=PP&f%5Bfaculty%5D=RE&f%5Bfaculty%5D=TW&f%5Bfaculty%5D=WE&f%5Bstatus%5D=public&f%5Btype%5D=dissertation

This query only yields only 1 record. Why? Because the "department" field of that record contains faculty information and so the "faculty" field is filled in: (faculty = LA)

```
"department":[{"id":"LA26","tree":[{"id":"UGent"},{"id":"LA"},{"id":"LA26"}]},{"id":"KR01","tree":[{"id":"GUK"},{"id":"KR01"}]}]
```

That's not the case for this record:

```
"department":[{"id":"LA24","name":"Department of Green Chemistry and Technology"}]}]
```

Looking at the problematic records: they seem to have been added in the last few days - post launch. So, it seems like the UI doesn't pick up / include the entire hierarchical information required to figure out and fill in the "faculty" field.
