### ISSUE TITLE
Calculation error in dashboard: complete number is not the total of all visible numbers

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#858]
# Bug

Calculation error in dashboard: complete number is not the total of all visible numbers.

_Note: we are not taking into account the "no department" one here._

## Steps to reproduce

1. Go to dashboard
2. Go to datasets or publications
3. Count all records, for example for datasets: 39+4+6+11+3+1+1+5+12 = 82
4. Compare with total, for example for datasets: 78 VS 82

Datasets
![Image](https://user-images.githubusercontent.com/1572885/203983138-7cebfd03-76d3-46d2-9e74-0f6ceda2b16d.png)

Publications
![Image](https://user-images.githubusercontent.com/1572885/203983360-733a3885-9601-4548-af0f-939395eae1e1.png)

**Comment by netsensei** [comment]
@mietcls This isn't a bug. It's a question of "What exactly are we counting here?"

Some publications are associated with more then 1 faculty which causes them to become part of the count for multiple faculties.  However, the "all" column, shows the count for all discrete publications. Which will be a lower number because of de-duplication.

For instance, if a publication with number 12345 is tied to faculty WE and LW,  it will show  these numbers:

All = 1
WE = 1 (id: 12345)
LW = 1 (id: 12345)

If we have 2 publications, with one being associated with 1 faculty, and the other one being associated with 2 faculties:

All = 2
LW = 2  (id: 12345, id: 23456)
WE = 1 (id: 12345)

The "all" column just displays the exact number of unique publications across all faculties.  If you want the "all" column to match with the aggregate sum of the numbers for each faculty, then you're not counting unique publications, you're counting the number of relationships between publications and faculties. Which is a different thing.

The "all" row" is correct: it's the number of unique publications per faculty across all publication types (since publications can have only a single publication type).

The "all/all" cell in the top left also is a separate number from the aggregate totals of the faculties and the publication types in the "all" column and "all" rows. It's the grand total of all discrete publications which are Unclassified & belong to at least one of the faculties in the dashboard.

If this remains too confusing, we might need to rethink about renaming the "all" column / row header; or even split those off from the main table; or add a help / reminder text to make sure everyone understand how things are counted.

**Comment by mietcls** [comment]
Ha! Interesting. Thank you.
