### ISSUE TITLE
search does not return partial text match results

### ISSUE THREAD

**Issue by sdebodt** [ugent-library/biblio-backoffice#89]
**Describe the improvement**
When searching the publications using the search box, I do not get results when the search term as part of a word of e.g. the publication title. For instance, when I search with "della", I do not get the publication that has the word "DELLAs" in the title (Biblio ID: 4419918). (The result I get has the complete word "DELLA" in the abstract, so that is correct)

**To Reproduce**
1. Go to 'Publications overview' page
2. Enter search term in search box
3. Click enter
4. Check results

**Expected behavior**
I expect to be able to search with part of words as well as complete words.

**Screenshots**
part of word results:
![image](https://user-images.githubusercontent.com/72742841/141472580-caec640e-ba95-45c1-a614-a5636e1b386f.png)

complete word results:
![image](https://user-images.githubusercontent.com/72742841/141472608-2ee5227e-9509-48cb-9583-c8fc8206ec1c.png)

**Comment by sdebodt** [comment]
Dependency on LibreCat database. To be revisited later.

**Comment by nicolasfranck** [comment]
Note to self: use ES internal field `_score` to sort on

**Comment by mietcls** [comment]
@nicolasfranck is this something we can do now?

**Comment by nicolasfranck** [comment]
@mietcls it's doable, but it requires

* adding an extra edge ngram field, that contains data from other fields. @nics I see that fields `contributor.ngram` and `contributor.phrase_ngram` contain contributor names, and are now used during search. Why not a common field for ngrams (and that contains names and titles)? We already have a common field `all` that now contains titles and contributor names only. It would mean though that we cannot distinguish between "match on title" and "match on contributor" when it comes to sorting. But I guess scoring should be very low for ngrams anyway?
* probably more data, and indexing time. Anyway scoring should be very low, and minimum length not too low (i.e only when words are longer than 2 characters), as it would bring "crap" results on top.  Also creating ngrams from several sources should be created with caution. We already search in multiple fields, so that someone may enter both an author's name and part of the title (e.g. `Plato politeia`). I've tried this in the past, and saw that people where confused on why they got results. The more fields you add, the greater the confusion becomes

**Comment by mietcls** [comment]
Closing this since it fits into a bigger search question.
