### ISSUE TITLE
Are our citation representations off?

### ISSUE THREAD

**Issue by mietcls** [ugent-library/biblio-backoffice#941]
# Question

Are our citation representations off?

## Context

“Bij het doctoraat van Akbar Dadkhah (https://biblio.ugent.be/publication/01GKVBTCCFZDG9TYZYDC0TDFYP), zijn de citatiestijlen precies door elkaar gehaald, zie screenshot.
We gebruiken meestal IEEE-stijl (met een nummer tussen vierkante haakjes, het jaar achteraan., etc.) maar bij Akbar’s doctoraat klopt de IEEE-citatie niet. Het is precies alsof APA en IEEE omgewisseld zijn, want onder APA zie ik wat ik zou verwachten bij IEEE.”

![Image](https://user-images.githubusercontent.com/1572885/209162379-59055319-d93c-4ec8-b579-444fdfecf29d.png)

**Comment by nicolasfranck** [comment]
Same here: https://bibliotest.ugent.be/publication/5869270

**Comment by nicolasfranck** [comment]
Ok, that is a bug caused by recent changes (by me) in that citeproc server (when using the `/cites` endpoint that accepts multiple style arguments at once). For some reason the styles are randomly (!) assigned to the wrong citation style (so you will find other mismatches too). I found the cause and will submit a PR soon.
This will requires reindexation of the biblio frontend.

**Comment by mietcls** [comment]
Thanks for looking into it! I'll communicate to the reviewers when it is fixed.

**Comment by nicolasfranck** [comment]
should be fixed

**Comment by netsensei** [comment]
Closing this, ready for testing.

**Comment by mietcls** [comment]
Confirmed, this works
